new_run:
  entity: "geniac"
  project: "llm-leaderboard-test"
  run_name: "[test]run_integration"

old_runs:
  - entity: "geniac"
    project: "llm-leaderboard-test"
    run_id: "mi3rxo2n"
    datasets:
      - jaster_ja_0_shot
      - jaster_ja_4_shot
      # - jaster_en_0_shot
      # - jaster_en_4_shot
      - mtbench_ja
      - mtbench_en
  - entity: "geniac"
    project: "llm-leaderboard-test"
    run_id: "rqkttbnp"
    datasets:
      # - jaster_ja_0_shot
      # - jaster_ja_4_shot
      - jaster_en_0_shot
      - jaster_en_4_shot
      # - mtbench_ja
      # - mtbench_en

