run_chain: true

new_run:
  entity: "geniac"
  project: "llm-leaderboard-test"
  run_name: "[test]" # this run_name will be used as the name of run in leaderboard. Can be changed later

old_runs:
  - run_path: "geniac/llm-leaderboard-test/mi3rxo2n"
    tasks:
      - jaster_ja_0_shot
      - jaster_ja_4_shot
      # - jaster_en_0_shot
      # - jaster_en_4_shot
      - mtbench_ja
      - mtbench_en
  - run_path: "geniac/llm-leaderboard-test/mi3rxo2n"
    tasks:
      # - jaster_ja_0_shot
      # - jaster_ja_4_shot
      - jaster_en_0_shot
      - jaster_en_4_shot
      # - mtbench_ja
      # - mtbench_en